---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd-smi-helm-repo
  namespace: kommander-flux
spec:
  interval: 2m0s
  url: https://linkerd.github.io/linkerd-smi