apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkerd.yaml
  - linkerd-viz.yaml
  - linkerd-multicluster.yaml
  - linkerd-smi.yaml
  - ../../../helm-repositories/linkerd