---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-smi
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-smi
      sourceRef:
        kind: HelmRepository
        name: linkerd-smi-helm-repo
        namespace: kommander-flux
      version: 0.2.0
  dependsOn:
    - name: linkerd-multicluster
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-smi
  valuesFrom:
    - kind: ConfigMap
      name: linkerd-smi-2.12-defaults
  targetNamespace: linkerd-smi