---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: linkerd-helm-repo
        namespace: kommander-flux
      version: 1.9.4
  dependsOn:
    - name: linkerd-crds
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-control-plane
  valuesFrom:
    - kind: ConfigMap
      name: linkerd-2.12-defaults
  targetNamespace: linkerd

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-crds
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: linkerd-helm-repo
        namespace: kommander-flux
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  targetNamespace: linkerd


