---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-multicluster
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-multicluster
      sourceRef:
        kind: HelmRepository
        name: linkerd-helm-repo
        namespace: kommander-flux
      version: 30.2.4
  dependsOn:
    - name: linkerd-viz
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true      
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-multicluster
  valuesFrom:
    - kind: ConfigMap
      name: linkerd-multicluster-2.12-defaults
  targetNamespace: linkerd-multicluster

